### ISSUE TITLE
Doesn't work inside a theme

### ISSUE THREAD

**Issue by famfam** [mustardBees/cmb_field_map#10]
I'm trying to put it inside theme but doesn't work.

CMB works ok.
Others metaboxes are showing fine.

This one doesn't show map and reviewing with Firebug find this error inside script.js called:
You don't have permission to access ...addresstomytheme.../inc/metaboxes/cmb_field_map/js/script.js
on this server.

When I comment this line define( 'PW_GOOGLE_MAPS_URL', plugin_dir_url( **FILE** ) ); and replace by define( 'PW_GOOGLE_MAPS_URL', trailingslashit( get_stylesheet_directory_uri() . '/inc/metaboxes/cmb_field_map/cmb-field-map.php' ) );

I found this error: <b>Fatal error</b>:  Call to undefined function add_filter() in <b>...addresstomytheme...\inc\metaboxes\cmb_field_map\cmb-field-map.php</b> on line <b>30</b><br />

**Comment by danieljulia** [comment]
I think this is important, the ability of CMB2 to be used inside a theme without a plugin is a great functionality

**Comment by mustardBees** [comment]
Hi @danieljulia. If you're going to include this field directly in your theme, you just need to ensure [the scripts and styles are loaded from the correct location](https://github.com/mustardBees/cmb_field_map/blob/v2.1.1/cmb-field-map.php#L80-81).

There is an alternative which I recommend you look into. Check out [TGM Plugin Activation](http://tgmpluginactivation.com/). Not only can you define plugin dependencies from the WordPress plugin directory, you can also bundle a plugin's ZIP file in with your theme. However, this does add an extra step for the end user to install the required plugins.

**Comment by danieljulia** [comment]
great, i fixed it changing the location, but i think it would be really nice if it could work out of the box inside a theme without plugins, for instance in a multisite installation sometimes is complicated to activate plugins.

Thanks for your work! it's great
