### ISSUE TITLE
Unable to save coordinates in repeatable groups

### ISSUE THREAD

**Issue by pasqualevitiello** [mustardBees/cmb_field_map#12]
Hello there,

I am currently using your custom field inside repeatable groups but it is unable to save coordinates. Would you please help me to figure out how to fix the issue?

Cheers,
-P

**Comment by cliffordp** [comment]
I assume this is still an issue?

What needs to be done to fix this?

**Comment by mustardBees** [comment]
I have added created a [repeatable-groups](https://github.com/mustardBees/cmb_field_map/tree/repeatable-groups) branch. Could you guys test it out? Any feedback greatly appreciated.

**Comment by ramiroazar** [comment]
Thank you for the update @mustardBees. I was in the process of addressing this same issue, but your repeatable-groups branch is functioning correctly.

- **setup_pw_map** function is correctly reinitialized on **cmb2_add_row** event
- **name** attributes of hidden **input** fields are populated with correct **value**

I can verify that each map instance works correctly and the coordinates are saved and retrievable.

Thank you for resolving the issue.

**Comment by mustardBees** [comment]
Thanks for taking a look @ramiroazar. I've just merged this in and released [v2.1.0](https://github.com/mustardBees/cmb_field_map/releases/tag/v2.1.0).
