### ISSUE TITLE
CMB2 - is it compatible?

### ISSUE THREAD

**Issue by sb-lc** [mustardBees/cmb_field_map#16]
hi, is this field ready to go with CMB"?

array(
    'name' => 'Location',
    'desc' => 'Drag the marker to set the exact location',
    'id' => $prefix . 'location',
    'type' => 'pw_map',
    'sanitization_cb' => 'pw_map_sanitise',
),

i use the above field declaration and the field is empty, do I need to adjust something?

**Comment by marioktian** [comment]
what is the code to show it in the front-end
