### ISSUE TITLE
CMB field map not working with CMB2 shortcode

### ISSUE THREAD

**Issue by kidesigner** [mustardBees/cmb_field_map#20]
CMB field map not working with CMB2 shortcode. See bug:
<pre>
ReferenceError: postboxes is not defined
</pre>

**Comment by mustardBees** [comment]
I've released [v2.1.1](https://github.com/mustardBees/cmb_field_map/releases/tag/v2.1.1) which should prevent this JS error.

Can you grab the latest version and let me know if you have any further trouble.
