### ISSUE TITLE
Feature suggestion - possibility to save location data instead of just lat / lon

### ISSUE THREAD

**Issue by andrejm** [mustardBees/cmb_field_map#22]
This extension serves you very well in a use case, where you save a point in the map in order to show it again in the frontend.

But what about the case, when you want to output certain information about the location in the frontend (maybe even without showing a google map) - street address, city, country... 

Wouldn't it be useful to add the possibility to save certain pieces of address just like you can save lat / lon separately?

**Comment by mustardBees** [comment]
I'm not sure how much interest there would be in this feature. Having separate CMB2 fields alongside the map field gives the freedom/flexibility to collect address data in any format. For example you could use a textarea or any number of separate address lines.

Google has a nice [example of what you're after](https://developers.google.com/maps/documentation/javascript/examples/places-autocomplete-addressform). Please feel free to make use of this project as a starting point for your own field.

**Comment by cliffordp** [comment]
Just what I came looking for too! :-)

And nice link to Google.

I'd definitely like to see this added if you're counting votes! :100:

**Comment by JakeCobley** [comment]
+1 Would also like to see this added!

**Comment by DylanDunlop** [comment]
I needed to store the address along with the latitude and longitude of the location, but didn't see the need for adding additional fields to be filled out. I modified the plugin to store the address in the database along side the latitude and longitude.

Hopefully it will be useful to someone in the future: https://github.com/DylanDunlop/cmb_field_map

**Comment by timiwahalahti** [comment]
Thanks @DylanDunlop for forking and adding address saving!

@mustardBees: I think that fork should be merged into this repository, or at least pointed in README, because CMB2 documentation links to this repository. Maybe the address saving could be determined with option?
