### ISSUE TITLE
Is Repeatable?

### ISSUE THREAD

**Issue by ruturaaj** [mustardBees/cmb_field_map#33]
Hello,

I just discovered this field and want to know if this field supports use in Group. Is this field Repeatable? Documentation of this field does not reveal this info, hence asking.

Waiting for your reply...

Cheers,

Ruturaaj.

**Comment by mustardBees** [comment]
Hi @ruturaaj. No problem. You can use the field in a repeatable group.

**Comment by ruturaaj** [comment]
Thanks so much for your quick reply. I tried to set the "Repeatable" as True but it didn't work for me. Perhaps the field works within "Group". I will check it out and will revert back.

**Comment by ruturaaj** [comment]
I checked and I confirm that the field worked in Group. The "Repeatable" property does not work for this field; but the Map field works good in Repeatable Group.
