### ISSUE TITLE
Adoption

### ISSUE THREAD

**Issue by jdcauley** [mustardBees/cmb_field_map#40]
Hey,

Are you continuing to support this project, is there something I can help with?

Jordan

**Comment by mustardBees** [comment]
Hey @jdcauley. Still maintained! The field type is used widely across iWeb's portfolio as well as my own side projects. I’m always open to collaboration and pull requests.

I've just pushed an [update to the Select2 field type](https://github.com/mustardBees/cmb-field-select2/releases). I’m going to give this map field type some attention in the very near future. Hopefully satisfying most feature requests/closing up issues.

Immediate plans for the map field include:

- Look at the potential impact of saving the search field text alongside lat/long
- Ability to filter asset URLs to allow the field to be bundled along with themes/plugins without having to modify the files
- Ability to filter the default starting point (at the moment it’s over the UK)
- The documentation needs updating and I plan to include some front end examples

If you have any feature suggestions, please open an issue for each. You’re also more than welcome to [get in touch directly](https://www.philwylie.co.uk/contact/) :)

**Comment by timiwahalahti** [comment]
Hi @mustardBees,

I really enjoy using this field type but it definitely does have few flaws to fix. You're plans for further development sounded nice, and i wanted to give some help. Please check PR #42 which adds most requested functionalities and give some feedback ^^

**Comment by mustardBees** [comment]
@timiwahalahti Thanks for the kind words, and more importantly, the pull request! It's much appreciated.

I will pick this up next week.
