### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by nebojisa** [mustardBees/cmb_field_map#43]
Fatal error: Cannot redeclare class PW_CMB2_Field_Google_Maps in /home/site/public_html/wp-content/plugins/cmb_field_map-master/cmb-field-map.php on line 16.

**Comment by mustardBees** [comment]
It sounds like you already have a copy of the field running *somewhere*. Perhaps a theme/plugin is also loading a copy. Try searching your project for the class name `PW_CMB2_Field_Google_Maps `.
