### ISSUE TITLE
API Key Is required?

### ISSUE THREAD

**Issue by jdgwf** [mustardBees/cmb_field_map#48]
API Key Is required in our instance. I was able to fix this by hardcoding the API key in the Google Maps script enqueue. It might behooves to add this as an option or setting in the admin :)

**Comment by phh** [comment]
While we wait for this to get merged in here is a little filter that might help you:

```
add_filter( 'cmb2_render_pw_map', function() {
	wp_deregister_script( 'pw-google-maps-api' );
	wp_register_script( 'pw-google-maps-api', '//maps.googleapis.com/maps/api/js?libraries=places&key=<API-KEY>', null, null );
}, 12 );
```

**Comment by rasmustaarnby** [comment]
This is now possible. See #58

**Comment by jdgwf** [comment]
Closing ancient issue.
