### ISSUE TITLE
Add directions or open link in new page for directions

### ISSUE THREAD

**Issue by iamdigitaljoe** [mustardBees/cmb_field_map#52]
I am new to the whole Github experience and am working with the cmb_field_map but I for the life of me cannot add driving directions to the meta boxes php

**Comment by mustardBees** [comment]
Hi @iamdigitaljoe. This map field serves a fairly specific purpose. The field stores a set of coordinates into post meta. How you make use of this data on your front end is down to you.

You could use the [Google Maps Directions API](https://developers.google.com/maps/documentation/javascript/directions) to achieve an on-page directions lookup. Feel free to reverse engineer [this example](http://www.nviron.co.uk/contact/).

Alternatively, you could generate a link similar to:

```
https://www.google.co.uk/maps?daddr=51.461026,-0.138722
```
