### ISSUE TITLE
How installation?

### ISSUE THREAD

**Issue by vucumbra** [mustardBees/cmb_field_map#53]
Hi
i have not understand how install, i have read in documentation i must install like a normal plugin....but i have already cmb2, maybe i must put your folders into cmb2's folder? If yes where...
Thx

**Comment by mustardBees** [comment]
Hi @vucumbra. This field can be installed as another plugin alongside CMB2.

Download the zipped plugin from the [releases page](https://github.com/mustardBees/cmb_field_map/releases). Install as you would any other plugin. Make sure you have activated the plugin within WordPress.

Let me know if you have any further trouble.
