### ISSUE TITLE
Map not rendering properly

### ISSUE THREAD

**Issue by mannieschumpert** [mustardBees/cmb_field_map#7]
The map is rendering inconsistently. (see image)

When first entering a location in the search field, the map does not render properly. However, after clicking "Save Post", the map does render properly. Then when re-opening the post for editing, the map again does not render properly.

Any guesses as to what's happening? 
*Note: there's currently only one other plugin activated, and it doesn't add any JS, so a conflict is improbable.*
![screen shot 2014-08-29 at 12 21 51 pm](https://cloud.githubusercontent.com/assets/546544/4093140/7508dd96-2f99-11e4-93f9-d247ecd653d5.png)

**Comment by mustardBees** [comment]
Can you test this with the [repeatable-groups](https://github.com/mustardBees/cmb_field_map/tree/repeatable-groups) branch? I believe this fixes the issue.

If you could cast your eyes over the new code generally that would also be greatly appreciated :)
